### ISSUE TITLE
ModuleNotFoundError: No module named 'imgui'

### ISSUE THREAD

**Issue by evenblad3** [Aman-Anas/bge-imgui#1]
I installed imgui by `pip install imgui[full]` but I get this error: `ModuleNotFoundError: No module named 'imgui'`.
I also tried by copying the python module folder from the Python directory and pasting it inside the project directory, and then I get another error saying that there is no module named imgui.core.
![aaa](https://github.com/Aman-Anas/bge-imgui/assets/76159645/9e95693d-0070-4bc1-8dbe-d0bf69049f7c)

**Comment by Aman-Anas** [comment]
In order to use imgui, you need to make sure to install imgui into range engine's internal python install. you can do this from a text editor window like this:
```py
import subprocess
import sys
import os
 
python_exe = os.path.join(sys.prefix, 'bin', 'python')
target = os.path.join(sys.prefix, 'lib', 'site-packages')
 
subprocess.call([python_exe, '-m', 'ensurepip'])
subprocess.call([python_exe, '-m', 'pip', 'install', '--upgrade', 'pip'])

#example package to install
subprocess.call([python_exe, '-m', 'pip', 'install', '--upgrade', 'imgui_bundle', '-t', target])
subprocess.call([python_exe, '-m', 'pip', 'install', '--upgrade', 'Pillow', '-t', target])
 
print('DONE')
```

Then, you press the little run button rather than using any bricks to install it.
![image](https://github.com/Aman-Anas/bge-imgui/assets/41600372/c52c17c1-0acd-4534-8570-6e8c6797472e)

**Comment by Aman-Anas** [comment]
I'm actually pushing an update right now to use imgui_bundle instead of pyimgui, just a second.

**Comment by Aman-Anas** [comment]
Just updated the repo to use imgui_bundle since it has support for docking and a newer imgui version, so the above should work now

**Comment by chrisbradleyjones** [comment]
Thank you! That solved the issue.

**Comment by evenblad3** [comment]
Well, it looks like the problem still persits. The packages are installed successfully but I'm still getting this error: `ModuleNotFoundError: No module named 'imgui'`
I was able to download the package but unable to install it due to `PermissionError`.
I tried it again by running Range Engine as administrator, the packages were installed successfully but again the same error occurs.

**Comment by Aman-Anas** [comment]
> Well, it looks like the problem still persits. The packages are installed successfully but I'm still getting this error: `ModuleNotFoundError: No module named 'imgui'`
> I was able to download the package but unable to install it due to `PermissionError`.
> I tried it again by running Range Engine as administrator, the packages were installed successfully but again the same error occurs.

Where did the packages install? Try copying the install script again, I fixed a bug shortly after I sent it :P

To check if it installed the libs, go to your range engine 2.79 folder, and find python libs, navigate to site-packages. That should show all installed libraries.

**Comment by Aman-Anas** [comment]
Additionally, make sure you have re-cloned the repo before testing to get the update to imgui_bundle

**Comment by Aman-Anas** [comment]
Discussed on the RanGE discord, just had to ensure the `tomli` lib was also installed (since the gui_style feature reads from a toml file... this could be changed if it's a problem.)

The updated library install script is something like
```py
import subprocess
import sys
import os
 
python_exe = os.path.join(sys.prefix, 'bin', 'python')
target = os.path.join(sys.prefix, 'lib', 'site-packages')
 
subprocess.call([python_exe, '-m', 'ensurepip'])
subprocess.call([python_exe, '-m', 'pip', 'install', '--upgrade', 'pip'])

#example package to install
subprocess.call([python_exe, '-m', 'pip', 'install', '--upgrade', 'imgui_bundle', '-t', target])
subprocess.call([python_exe, '-m', 'pip', 'install', '--upgrade', 'Pillow', '-t', target])
subprocess.call([python_exe, '-m', 'pip', 'install', '--upgrade', 'tomli', '-t', target])

print('DONE')
```
